### ISSUE TITLE
CIFAR10 dataset

### ISSUE THREAD

**Issue by shruum** [hkunzhe/label_consistent_attacks_pytorch#1]
Hi,
Thanks for the pytorch repo.

I had two questions,

1. Where is the test set being generated?
2. I wanted to check if the different poisoned CIFAR10 datasets are accessible for download? It would be helpful if the ".npy" files were shared. My email is "sngowda42@gmail.com".

Thanks
Shruthi

**Comment by hkunzhe** [comment]
@shruum, Sorry for my late response.
1. Please refer to the class [`CleanLabelDataset`](https://github.com/hkunzhe/label_consistent_attacks_pytorch/blob/master/data/dataset.py#L8).
2. I've uploaded the  adversarially peturbed dataset to [Dropbox](https://www.dropbox.com/s/i8nmwfgohp46xyo/cifar_resnet_e8_a1.5_s100.npz?dl=0).
